export const MARKETING_BOOK_IMPORT_CONFIG = {
  sourceUrls: [
    'https://www.vinabook.com/products/kich-ban-thuc-chien',
    'https://www.vinabook.com/products/cach-tao-video-trieu-view',
    'https://www.vinabook.com/products/dat-ten-thuong-hieu-1',
    'https://www.vinabook.com/products/ung-dung-agile-marketing',
    'https://www.vinabook.com/products/manifest-marketing',
    'https://www.vinabook.com/products/cong-thuc-ban-hang-bat-bai',
    'https://www.vinabook.com/products/doi-moi-voi-intergrated-brand-thinking',
    'https://www.vinabook.com/products/thuat-canh-tranh',
    'https://www.vinabook.com/products/chien-luoc-marketing-thuc-chien',
    'https://www.vinabook.com/products/human-branding-nuoi-duong-thuong-hieu-ba-ng-su-thau-cam',
    'https://www.vinabook.com/products/inamori-kazuo-moi-ngay-mot-cau-noi-nang-tam-van-menh',
    'https://www.vinabook.com/products/the-ai-edge-khai-thac-the-manh-ai-trong-sales-va-marketing',
    'https://www.vinabook.com/products/inbox-marketing-nhieu-tac-gia',
    'https://www.vinabook.com/products/thay-truoc-doanh-thu-aaron-ross-marylou-tyler',
    'https://www.vinabook.com/products/marketing-truc-tiep-dan-s-kennedy',
    'https://www.vinabook.com/products/ban-hang-cho-nguoi-giau-dan-s-kennedy',
    'https://www.vinabook.com/products/bi-mat-traffic-russell-brunson',
    'https://www.vinabook.com/products/phan-tich-du-lieu-marketing-1',
    'https://www.vinabook.com/products/tro-choi-tam-ly-trong-marketing',
    'https://www.vinabook.com/products/nghe-thuat-ban-hang-cua-nguoi-huong-noi-tro-thanh-so-1-ban-hang-khi-la-nguoi-nhut-nhat',
    'https://www.vinabook.com/products/tam-ly-hoc-tich-cuc-trong-ban-hang-tang-tu-tin-tang-doanh-so-va-them-hanh-phuc',
    'https://www.vinabook.com/products/5-phut-chot-don',
    'https://www.vinabook.com/products/gam7-book-special-2020-marketing-thoi-binh-thuong-moi-san-sang-chuyen-dich-de-vuon-len',
    'https://www.vinabook.com/products/conversion-hacking-gia-tang-ty-le-chot-don-hang',
    'https://www.vinabook.com/products/p-kotler-tiep-thi-voi-tinh-than-doanh-chu-vuot-qua-su-chuyen-nghiep-de-huong-toi-sang-tao-lanh-dao-va-ben-vung',
    'https://www.vinabook.com/products/nghien-cuu-trong-marketing',
    'https://www.vinabook.com/products/marketing-trong-ky-nguyen-so',
    'https://www.vinabook.com/products/content-tiktok',
    'https://www.vinabook.com/products/cau-view-va-kinh-te-chu-y',
    'https://www.vinabook.com/products/trai-nghiem-khach-hang-xuat-sac-tai-ban-2024',
    'https://www.vinabook.com/products/mega-livestream-be-noi-tang-bang-chim',
    'https://www.vinabook.com/products/doanh-nghiep-cong-hien',
    'https://www.vinabook.com/products/the-customer-rules-39-nguyen-tac-cot-loi-de-mang-toi-dich-vu-dinh-cao-2',
    'https://www.vinabook.com/products/the-customer-rules-39-nguyen-tac-cot-loi-de-mang-toi-dich-vu-dinh-cao-1',
    'https://www.vinabook.com/products/khung-hoang-khong-bat-dau-tu-truyen-thong',
    'https://www.vinabook.com/products/ux-content',
    'https://www.vinabook.com/products/bi-kip-viet-content-dinh-cao',
    'https://www.vinabook.com/products/marketing-dich-vu',
    'https://www.vinabook.com/products/chuyen-gia-phan-tich-du-doan-marketing',
    'https://www.vinabook.com/products/7-don-bay-tang-do-tin-nhiem-thuong-hieu',
    'https://www.vinabook.com/products/chien-luoc-ngam-trong-marketing',
    'https://www.vinabook.com/products/marketing-trieu-don-hang',
    'https://www.vinabook.com/products/tam-ly-hoc-hanh-vi-trong-marketing',
    'https://www.vinabook.com/products/marketing-cam-xuc',
    'https://www.vinabook.com/products/nhung-chu-cho-ban-hang-lam-bung-no-thu-nhap-ma-khong-can-chien-luoc-tan-cong',
    'https://www.vinabook.com/products/tu-thuong-hieu-va-chat-luong-den-tuyen-sinh-hieu-qua'
  ],
  categoryLabel: 'S\u00e1ch Kinh T\u1ebf',
  subcategorySlug: 'marketing-ban-hang',
  subcategoryLabel: 'Marketing - Ban Hang',
  imagesRootSegments: ['assets', 'images', 'books', 'marketing-ban-hang'],
  filesListName: '__marketing_files.txt',
  mergeStrategy: 'replaceSubcategorySlice',
  targetHandleScope: 'slice',
  resetImagesRootBeforeRun: true,
  clearProductDirectoryBeforeWrite: true,
  skipSoldOut: false,
  includeSourceProductId: false,
  fallbackToHtmlMetaImages: false,
  pruneHandles: []
};
